### ISSUE TITLE
Examples using WAV / MP3 files

### ISSUE THREAD

**Issue by nicolaspanel** [voixen/voixen-vad#1]
Hi @patlevin, thank you for sharing this.

Could you please provide examples with data from wav or/and mp3 files?

Best regards

**Comment by patlevin** [comment]
Hi @nicolaspanel,

Sorry for the delay, but I had very little time due to private and work issues.
I will add an example app that processes MP3 files to repository. Expect an update to arrive in the next few days.

Best regards

**Comment by nicolaspanel** [comment]
Thank you :+1:

**Comment by patlevin** [comment]
The /examples/waveform folder now contains a fully functional sample application that uses both the MP3 decoder and the VAD library. The example is fully documented and should provide a useful starting point.
